version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_OPENROUTESERVICE_KEY=${NEXT_PUBLIC_OPENROUTESERVICE_KEY}
    container_name: naviguard-web
    restart: always
    ports:
      - "5192:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEXT_PUBLIC_OPENROUTESERVICE_KEY=${NEXT_PUBLIC_OPENROUTESERVICE_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NODE_ENV=production
    env_file:
      - .env


