'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { createBrowserSupabaseClient } from '@/lib/supabase/client';
import { Loader2, Lock, AlertCircle, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function MfaChallengeClient() {
  const router = useRouter();
  const supabase = createBrowserSupabaseClient();

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [factorId, setFactorId] = useState<string | null>(null);
  const [otpCode, setOtpCode] = useState('');
  const [verifying, setVerifying] = useState(false);
  const [success, setSuccess] = useState(false);

  useEffect(() => {
    async function checkFactors() {
      try {
        // 1. Fetch user to verify active session
        const { data: { user }, error: userErr } = await supabase.auth.getUser();
        if (userErr || !user) {
          router.replace('/login');
          return;
        }

        // 2. Fetch AAL levels
        const { data: mfaData, error: mfaErr } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel();
        if (mfaErr) throw new Error(mfaErr.message);

        // If user session is already verified (AAL2), skip challenge
        if (mfaData && mfaData.currentLevel === 'aal2') {
          router.replace('/admin/dashboard');
          return;
        }

        // 3. Fetch active factors list
        const { data: factors, error: listErr } = await supabase.auth.mfa.listFactors();
        if (listErr) throw new Error(listErr.message);

        // Find active TOTP factor
        const activeTotp = factors?.totp?.find((f: any) => f.status === 'verified');
        if (!activeTotp) {
          // No active factor found; force MFA setup
          router.replace('/admin/mfa-setup');
          return;
        }

        setFactorId(activeTotp.id);
        setLoading(false);
      } catch (err: any) {
        setError(err.message || 'An error occurred during verification initialization.');
        setLoading(false);
      }
    }

    checkFactors();
  }, [router, supabase]);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!factorId || otpCode.length !== 6) return;

    setError(null);
    setVerifying(true);

    try {
      // Create verification challenge
      const { data: challengeData, error: challengeErr } = await supabase.auth.mfa.challenge({
        factorId,
      });

      if (challengeErr) throw new Error(challengeErr.message);

      // Verify OTP code
      const { data: verifyData, error: verifyError } = await supabase.auth.mfa.verify({
        factorId,
        challengeId: challengeData.id,
        code: otpCode,
      });

      if (verifyError) throw new Error(verifyError.message);

      setSuccess(true);
      setVerifying(false);
      
      // Redirect to Admin Dashboard
      router.push('/admin/dashboard');
    } catch (err: any) {
      setError(err.message || 'Invalid authentication code. Please try again.');
      setVerifying(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-slate-950 text-white">
        <Loader2 className="w-10 h-10 text-primary animate-spin mb-4" />
        <p className="text-slate-400 text-sm font-medium">Initializing Multi-Factor Authentication Challenge...</p>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen bg-slate-950 items-center justify-center p-6 relative overflow-hidden">
      {/* Background Graphic elements */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-[120px] pointer-events-none" />

      <div className="w-full max-w-md bg-slate-900/40 border border-slate-800/80 backdrop-blur-2xl rounded-3xl p-8 shadow-2xl relative z-10 space-y-6">
        
        {/* Header */}
        <div className="space-y-2 text-center">
          <div className="flex items-center justify-center w-12 h-12 bg-primary/10 border border-primary/20 rounded-2xl mx-auto text-primary mb-3">
            <Lock className="w-5 h-5" />
          </div>
          <h2 className="text-2xl font-black text-white tracking-tight leading-tight">Admin MFA Verification</h2>
          <p className="text-slate-400 text-xs max-w-xs mx-auto leading-relaxed">
            Enter the 6-digit security code generated by your Authenticator app.
          </p>
        </div>

        {error && (
          <div className="flex items-start gap-3 p-4 bg-red-950/40 border border-red-800/50 rounded-2xl text-red-300 text-xs animate-in shake duration-200">
            <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
            <div className="font-medium leading-relaxed">{error}</div>
          </div>
        )}

        {/* Challenge Form */}
        <form onSubmit={handleVerify} className="space-y-4">
          <input
            type="text"
            maxLength={6}
            placeholder="Enter 6-digit code"
            disabled={verifying || success}
            value={otpCode}
            onChange={(e) => setOtpCode(e.target.value.replace(/\D/g, ''))}
            className="block w-full py-3.5 px-4 bg-slate-950 border border-slate-800 focus:border-primary/50 text-white rounded-xl text-center text-lg font-bold font-mono tracking-widest transition focus:outline-none focus:ring-2 focus:ring-primary/20"
          />

          <button
            type="submit"
            disabled={verifying || success || otpCode.length !== 6}
            className="flex items-center justify-center w-full py-3.5 px-4 bg-primary hover:bg-primary-dark text-white rounded-xl text-sm font-semibold transition hover:shadow-lg shadow-primary/25 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {verifying ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin mr-2" />
                Authorizing session...
              </>
            ) : success ? (
              'Authentication Verified'
            ) : (
              'Verify Identity'
            )}
          </button>
        </form>

        {/* Back Link */}
        <div className="text-center pt-2">
          <Link
            href="/login"
            className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition font-medium"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to sign in page
          </Link>
        </div>

      </div>
    </div>
  );
}
